# Generated by Django 4.0.5 on 2022-07-04 19:37

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('itsp', '0006_alter_wingcleaning_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='Contact_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
