# Generated by Django 4.0.5 on 2022-07-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsp', '0007_alter_cleaning_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='Contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
