# Generated by Django 4.0.5 on 2022-07-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsp', '0009_cleaning_pending_alter_cleaning_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaning',
            old_name='Pending',
            new_name='Cleaning_done',
        ),
    ]
